main:
	

clean:
	rm -f *.fasta.I20	
	rm -f *.fasta.tab
	rm -f *.fasta.err	
	rm -f *.fasta.map
	rm -f *.fasta.hdr
	rm -f *.fasta.raw
	rm -f *.fasta.sym
	rm -f RESULTS.fasta.*
	rm -f cluster-*.IDs
	rm -f cluster-*.fasta
	rm -f out.*.blastfile.I20
	rm -f dump.out.*.blastfile.I20
	rm -f formatdb.log
