#!/usr/bin/ruby

Dir.glob("input-*").each do |old_name|
  if old_name =~ /^input-([0-9]*)$/
    cmd = "/bin/mv #{old_name} #{$1}-input"
    `#{cmd}`
  else
    STDERR.puts "WARNING: Bad filename #{old_name}"
  end
end
